DATA_PATH = '../data/chest_xray/'
TEST_DATA_PATH = 'test'
TRAIN_DATA_PATH = 'train'
VAL_DATA_PATH = 'val'
DATA_NORMAL_CASES_PATH = 'NORMAL'
DATA_PNEUMONIA_CASES_PATH = 'PNEUMONIA'
RESULT_PATH = '../result/'

EPOCHS = 10
BATCH_SIZE = 16
